// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseBgImage: typeof import('./src/components/BaseBgImage.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseButtonGroup: typeof import('./src/components/BaseButtonGroup.vue')['default']
    BrewGrid: typeof import('./src/components/menu/BrewGrid.vue')['default']
    BrewGridItem: typeof import('./src/components/menu/BrewGridItem.vue')['default']
    BrewPage: typeof import('./src/pages/BrewPage.vue')['default']
    DataDisplay: typeof import('./src/components/DataDisplay.vue')['default']
    IconArchive: typeof import('./src/components/icons/IconArchive.vue')['default']
    IconBlank: typeof import('./src/components/icons/IconBlank.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconCheckCircle: typeof import('./src/components/icons/IconCheckCircle.vue')['default']
    IconChevronRight: typeof import('./src/components/icons/IconChevronRight.vue')['default']
    IconCoffee: typeof import('./src/components/icons/IconCoffee.vue')['default']
    IconCommand: typeof import('./src/components/icons/IconCommand.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconMoon: typeof import('./src/components/icons/IconMoon.vue')['default']
    IconPause: typeof import('./src/components/icons/IconPause.vue')['default']
    IconPlay: typeof import('./src/components/icons/IconPlay.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconRefreshCw: typeof import('./src/components/icons/IconRefreshCw.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconStar: typeof import('./src/components/icons/IconStar.vue')['default']
    IconSun: typeof import('./src/components/icons/IconSun.vue')['default']
    IconX: typeof import('./src/components/icons/IconX.vue')['default']
    LibraryMenu: typeof import('./src/components/menu/LibraryMenu.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    MenuPage: typeof import('./src/pages/MenuPage.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RecipeStepListItem: typeof import('./src/components/RecipeStepListItem.vue')['default']
    SettingsMenu: typeof import('./src/components/menu/SettingsMenu.vue')['default']
  }
}

export {}
